### ISSUE TITLE
switch between cards?

### ISSUE THREAD

**Issue by rrodriguezsandchez** [cdaein/mica-gd405#5]
I am trying to make it so that the right click gives you one the title of the movie while the left one gives you the release date.
<img width="552" alt="Screen Shot 2019-03-25 at 12 28 46 AM" src="https://user-images.githubusercontent.com/46931252/54895255-16bba280-4e95-11e9-84ee-ba3b3a1d31f0.png">
<img width="481" alt="Screen Shot 2019-03-25 at 12 29 20 AM" src="https://user-images.githubusercontent.com/46931252/54895258-1c18ed00-4e95-11e9-9c4b-d8334b684cfc.png">

**Comment by rrodriguezsandchez** [comment]
<img width="823" alt="Screen Shot 2019-03-25 at 12 30 42 AM" src="https://user-images.githubusercontent.com/46931252/54895299-4d91b880-4e95-11e9-97e8-fa646cac411e.png">

**Comment by cdaein** [comment]
I guess you want the functions to run continuously, not only while a mouse is being pressed. In that case, introduce a new variable that stores the current state:

```java
int scene = 0;

void setup() {
  size(500, 500);
}

void draw() {
  background(123);
  
  if (scene == 0) {
    one();
  } else if (scene == 1) {
    two();
  }
}

void mousePressed() {
  if (mouseButton == LEFT) {
    scene = 0;
  } else if (mouseButton == RIGHT) {
    scene = 1;
  }
}

void one() {
  line(0, 0, width, height);
}

void two() {
  ellipse(width/2, height/2, 50, 50);
}
```
